language: node_js
sudo: false
node_js:
  - "4.6"
  - "5.12"
  - "6.9"
  - "7.2"
script: "npm run-script test-travis"
before_script:
  - mysql -u root testbase < test/db.sql
after_script: "npm install codeclimate-test-reporter && cat ./coverage/lcov.info | codeclimate-test-reporter"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: d2a8cd304286762ce24ac188ba959f3c2260737990297e906d08f48348bb34d3
env:
  - CXX=g++-4.8